#!/bin/sh
set -e

# Automatically added by dh_python2:
if which pycompile >/dev/null 2>&1; then
	pycompile -p inkscape /usr/share/inkscape
fi

# End automatically added section
# Automatically added by dh_installdeb/11.1.4ubuntu1
dpkg-maintscript-helper rm_conffile /etc/bash_completion.d/inkscape 0.91-6\~ -- "$@"
# End automatically added section
