#!/bin/sh
set -e
# Automatically added by dh_installdeb/11.1.4ubuntu1
dpkg-maintscript-helper rm_conffile /etc/bash_completion.d/inkscape 0.91-6\~ -- "$@"
# End automatically added section

# Automatically added by dh_python2:
if which pyclean >/dev/null 2>&1; then
	pyclean -p inkscape 
else
	dpkg -L inkscape | grep '\.py$' | while read file
	do
		rm -f "${file}"[co] >/dev/null
  	done
fi

# End automatically added section
